function Y = MSReduceROCCurve (X)
  % Reduce ROC curve by removing shadow points
  % Y = MSReduceROCCurve(X): In a matrix X as generated by 
  %   MSComputeROCCurve(), remove rows that correspond to 'shadow' points,
  %   i.e. points that are clearly inferior to neighboring points.
  
  M = [true; X(2:end-1,2) > X(1:end-2,2) & X(2:end-1,1) < X(3:end,1); true];
  Y = X(M,:);
end

